version: '3.7'

services:
  postgres:
    image: postgres:10.4
    container_name: pilger_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_SUPERUSER}
      POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD}
    ports:
    - "5432:5432"
    networks:
    - postgres
    volumes:
    - pilger_postgres:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    container_name: pilger_keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${DB_SUPERUSER}
      DB_PASSWORD: ${DB_SUPERUSER_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123atgfd
    ports:
    - 8080:8080
    depends_on:
    - postgres


networks:
  postgres:
    name: pilger-postgres
    driver: bridge


volumes:
  pilger_postgres: