version: '3.7'

services:
  openidc-auth-proxy:
    build: ./openidc-auth-proxy
    container_name: pilger_proxy
    restart: always
    ports:
    - "80:80"
    networks:
    - proxy 
  postgres:
    image: postgres:10.4
    container_name: pilger_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_SUPERUSER}
      POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD}
      KEYCLOAK_USER_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      KEYCLOAK_USER: ${DB_KEYCLOAK_USER}
    ports:
    - "5432:5432"
    networks:
    - database
    volumes:
    - pilger_postgres:/var/lib/postgresql/data
    - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  keycloak:
    image: jboss/keycloak
    container_name: pilger_keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${DB_KEYCLOAK_USER}
      DB_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123atgfd
    ports:
    - 8080:8080
    networks:
    - database
    - proxy
    depends_on:
    - postgres

networks:
  database:
    name: pilger-database
    driver: bridge
  proxy:
    name: pilger-proxy
    driver: bridge

volumes:
  pilger_postgres: