#!/bin/bash

set -e
export PGPASSWORD='$DB_SUPERUSER_PASSWORD'; 

psql -v ON_ERROR_STOP=1 --username "$DB_SUPERUSER" <<-EOSQL
    CREATE USER $KEYCLOAK_USER WITH ENCRYPTED PASSWORD '${KEYCLOAK_USER_PASSWORD}';
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
EOSQL




